### ISSUE TITLE
Moving annotations to Narratives

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#103]
As described in EMu Hour question 56, some Multimedia objects in LinEpig have annotations in the Notes field, clarifying details about the taxonomy, the specimen, or both - for example "Female undescribed. This female collected in Washington, det R. Crawford." These show up in the grey Notes box on the Detail page. These are now flagged with Note Type label = "Project Annotation" + Note Attributed to = “LinEpig”  (Q56 https://docs.google.com/document/d/1Uw6jIsLXJJW4oo9EApcqv5Wzihr-bhxyXAjKV4TtXlg/edit#heading=h.xaifoplqdavr)

We want to move these annotations into Narratives, splitting them into the part connected to Taxonomy ("Female undescribed.") and to Multimedia (info about this specimen), as appropriate. See draft batch uploads attached.

We would need to have the code look for Narratives records rather than Multimedia module Notes to populate the grey box. The separate parts should merge into the same paragraph, just as they do now. For example: https://linepig.fieldmuseum.org/multimedia/1388274

[LinEpig-Narrs-Taxo-draft.xlsx](https://github.com/nsandlin/linepig/files/11546959/LinEpig-Narrs-Taxo-draft.xlsx)
[LinEpig-Narrs-MM-draft.xlsx](https://github.com/nsandlin/linepig/files/11546960/LinEpig-Narrs-MM-draft.xlsx)

**Comment by peteherbst** [comment]
Are there some example Multimedia records set up on this fashion that I could use as examples for development?

**Comment by nsandlin** [comment]
There aren't any set up. We decided to use Narratives for both the Taxonomy part and the Multimedia part of the annotation. I sent a draft upload of the narratives for Taxonomy, and hope to post them next week. I could then create a couple of narratives for Multimedia that we could dev/test with.

Would you be able to upload them to Test? The current annotations are in the Notes field of the Multimedia record. So if we try to implement in production, we will have duplicate annotations.

We can just remove/commnent out the code that displays the MM Notes field once we're ready to go, and I can subsequently remove those notes for tidiness sake.

LMK your thoughts.

**Comment by peteherbst** [comment]
I can add them to the test site if you let me know of a few records to test. You just want the NarNarrative displayed from the attached enarratives record?

**Comment by peteherbst** [comment]
Great! Just let me know when the data gets into EMu so I can look for it. Then I'll set something up on the test site.

**Comment by nsandlin** [comment]
The Narrative records are now all imported. Here are a couple of examples: 
	MM irn 1388274 Asiceratinops kolymensis - Narr irn 12585 (Taxo info)
	MM irns 616592 and 1761816 Ceraticelus fastidiosus - Narr irn 12587 (Taxo info) and 12640 (specimen info)

The Taxo info note should show up on any Multimedia record that belong to that Taxonomy. The specimen info note should show up on all the Multimedia records its associated with as part of the same paragraph as the Taxo info sentence. 

Note that currently the same notes (in some case slightly different wording) are being pulled from NotNotes field of the Multimedia record.

**Comment by peteherbst** [comment]
I think I might have to meet with you to get full clarity on what we need for this, but I have some initial code updates on the test/dev site. I'll add the links here:

https://linepig.fieldmuseum.tech/multimedia/1388274
https://linepig.fieldmuseum.tech/multimedia/616592
https://linepig.fieldmuseum.tech/multimedia/1761816

I'll need to nail down the conditional logic with you sometime. For right now, the notes (annotations) are pulling from the narrative record associated with the multimedia's taxonomy.

**Comment by nsandlin** [comment]
Those look good as far as the narratives that go with the taxonomy. For the first one (1388274), that's all it gets - there is no narrative associated with its multimedia record. 

The other two have a narrative associated with the multimedia record itself. So that should be tacked on at the end of the note, which would then end up reading "Female undescribed. This female was collected in South Carolina in 1995 det by ML Draney." (There should already be a space character at the end of the taxo narrative.)

Let me know if I should add some additional info to the records, like an Other Number or whatever, to facilitate this.

**Comment by peteherbst** [comment]
Ok, I've added the narrative attached to the multimedia. Please take a look and let me know if we're good.

https://linepig.fieldmuseum.tech/multimedia/1388274
https://linepig.fieldmuseum.tech/multimedia/616592
https://linepig.fieldmuseum.tech/multimedia/1761816

**Comment by nsandlin** [comment]
Those are perfect!

**Comment by peteherbst** [comment]
Implemented via #107 

This code is now live on the prod site.
