### ISSUE TITLE
Make "Recently added" species names into links

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#106]
Rather than just listing the species that have been added in recent months, have the name link to all the images of that species. For example: 
  'Mermessus antraeus,' would become '<a href="https://linepig.fieldmuseum.org/search-results/genus/Mermessus/species/antraeus/keywords/none" target="_blank">Mermessus antraeus</a>,'

Note that this is a search result, not a request for the subset . It seems that just sticking the two terms into a prefab string at runtime is easier than having to look up the Taxonomy irn.

The idea was prompted by the fact that pages have different expiry dates, so species can be listed as "Recently added" but not yet be visible on the main page (although findable via an explicit search). But it also improves overall site usability.

**Comment by peteherbst** [comment]
Please take a look at the test site: https://linepig.fieldmuseum.tech/

The list differs from the live site, but I'm guessing that's the caching? Let me know what you think.

**Comment by nsandlin** [comment]
Yes!!! That's perfect. Just perfect.

**Comment by peteherbst** [comment]
Implemented via: ed4e4f251d39657a904f4c1a055322abef531276
