### ISSUE TITLE
Backlink to wrong-ID image

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#14]
For accountability and reference, when we replace a wrong image with a right one, we want to link back to the wrong one.

Background: LinEpig had an Multimedia image labeled Oreonetides vaginatus which turned out to be some different (currently not determined) species of Oreonetides. We replaced it with a correct image, and linked the old image to just the genus. And we created a Narrative with the correction.

Task: In cases like this, I want to include a link from the good image's detail.php page to the narrative (I can make a template for it, no sweat).

Attachment setup: According to Sharon, it's a direct attachment from the new Multimedia object to the Taxonomy and a reverse attachment from the Taxonomy to the Narrative.

Details:
MULTIMEDIA: NEW CORRECT IMAGE
Oreonetides vaginatus female epigynum - irn: 1245798
MulOtherNumber_tab: 537638 (irn of species)

MULTIMEDIA: OLD INCORRECT IMAGE
Oreonetides female epigynum - irn: 616726
MulOtherNumber_tab: 529895 (irn of genus)

TAXONONOMY
Oreonetides vaginatus - irn: 537638
"View Attachments" Narratives

NARRATIVE
Title: LinEpig image correction - irn: 4076
Narrative: "Image previously identified as Oreonetides vaginatus."
Purpose: Web Narrative
Type: Correction

**Comment by slobulas** [comment]
I have some code up, in a new branch. If you want to take a look at it, I'm going to create a pull request now. I hope we don't have any conflicts with your existing code.

**Comment by slobulas** [comment]
One thing to note in my code, for querying the Narrative, I'm just grabbing the first-attached Image. If you would like me to add some more additional checking, like for Type == 'correction', please let me know after you've merged the code.

**Comment by nsandlin** [comment]
Exciting! I'll take a look later today.  We are about to have a pie party
for Pi Day at my day job...   :-)

**Comment by slobulas** [comment]
I wish I could have pie!

**Comment by nsandlin** [comment]
You deserve pie!

**Comment by slobulas** [comment]
Example page: /multimedia/1245798

At the bottom, add in the proper Taxonomic identification (add attached Taxonomy record info) for the image, below it.

**Comment by slobulas** [comment]
I believe I have finally fixed this. Pulling changes to dev in a bit.

**Comment by slobulas** [comment]
Re-opening this. I have some issues to re-check.

**Comment by slobulas** [comment]
I have the code in place. We're going to need to fix this together the next time you come in. Something's weird. :)

**Comment by nsandlin** [comment]
Currently the old, wrong image (with ID only to genus) is showing up in primary and on home page, as well as in top of Detail page, and correct new image is nowhere. Also at the moment, all Detail pages show the same image as being previously incorrectly shown as itself.

**Comment by slobulas** [comment]
Description of how this functionality should work:

In the Multimedia record, in the MulOtherNumber_tab field is the Taxonomy IRN, on the Taxonomy record (for the records that had the incorrect image posted), we have a reverse-attached Narrative (NarNarrative) that holds the reference to the old Multimedia image that was incorrectly used.

**Comment by slobulas** [comment]
FINALLY have this fixed. Going to do a pull on dev shortly.

**Comment by nsandlin** [comment]
We had this fixed before the holidays - there was a "previously shown" image down below, but not it's gone. http://linepig.fieldmuseum.org/multimedia/1245798

Also, on the main page, this item is identified only as "Oreonetides" not "Oreonetides vaginatus" which I don't remember being the case before.

The "bad" image is also showing up on the main page (also identified only as "Oreonetides" which in its case is correct). I assume that's because it still had a "primary" keyword. I removed it Friday, but the change is not showing up on live; probably didn't happen due to the update.

We have another case coming up that will need to use the "bad backlink" functionality.

**Comment by slobulas** [comment]
We can take a look at this together again and try to see what's going on. Sorry!

**Comment by slobulas** [comment]
Be sure to update the production database!
