### ISSUE TITLE
Add "See images by this contributor" functionality

### ISSUE THREAD

**Issue by peteherbst** [nsandlin/linepig#16]
We have Creator fields, and we could search across those, exclude any Nina Sandlins and LinEpig's, and present the others as "See all by this contributor." 

CURRENT:
Image contributed by Gergin Blagoev. View collection record
BOLD systems taxon page

World Spider Catalog lookup

CONCEPT:
Image contributed by Gergin Blagoev.  See all images by this contributor 

View collection record
BOLD systems taxon page

World Spider Catalog lookup

And then have the "all images" link go to a Subset-like page; maybe this "Subset2" page should have a Flexbox right-column box where we can put some info about the contributor

**Comment by nsandlin** [comment]
Even better! We can just use the Contrib fields - nothing to filter. I had forgotten this nice detail. 

[Contribs.xlsx](https://github.com/nsandlin/linepig/files/242645/Contribs.xlsx)

**Comment by slobulas** [comment]
The DetContributor_tab is a list of Party IRNs of contributors?

**Comment by nsandlin** [comment]
Yes. See in the Contribs.xlsx attached above, it has IRNs in that field for externally-contributed images, and nulls for the images made here. (So currently only a small portion of the images will have them, but I hope over time more images will come in instead of having to borrow specimens.)

**Comment by slobulas** [comment]
AFTER LAUNCH

**Comment by peteherbst** [comment]
Do you want to close this out since the newest ticket has this covered?

**Comment by nsandlin** [comment]
This approach has bee superseded by the one outlined in Issue #62.
