### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#18]
For 500, 400 server error status code series

**Comment by nsandlin** [comment]
Here is a target page for the 404 response

[404.html.txt](https://github.com/nsandlin/linepig/files/473416/404.html.txt)
![mainpage](https://cloud.githubusercontent.com/assets/5316617/18529123/6d451e68-7a91-11e6-85a1-1c83b7a58f4e.png)

**Comment by slobulas** [comment]
Laravel comes with default error templates. We can use those for now.
