### ISSUE TITLE
Narratives-Sites trick to feed occurrence map

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#19]
This is for post-launch

Problem: We can make a set of Sites ("dittoed" where needed) to feed the LinEpig-specificoccurrence map. But what connects to the Sites? (Records are connected to Sites via their Collection Event; but images made from loaned specimens don't have collection events in EMu.)

Our plan: Instead, we use the Narratives module as an interstitial connector. The Narrative text becomes the collection information (which actually it would be nice to have, and was going to get left out in our original model). And we connect it with its dittoed Site (or the LinEpig-only Site, in those cases) via the Related Site field (SitSitesRef_tab) in Sites tab. We can even populate the Notes field (SitSitesNotes_tab) with some standard language about what we're doing. Wouldn't this give the user a Catalog-like experience of the specimen, without publishing out to GBIF etc and pre-empting (or duplicating) the lending institution's occurrence record.

This will require some data work to populate the Narratives with standardized html "pseudo-fields" to hold the collection/locality info, and some coding to present the map and info.

**Comment by slobulas** [comment]
AFTER LAUNCH

**Comment by nsandlin** [comment]
I am canceling this issue. There is no need to have an occurrence map of specimens that happen to be included in LinEpig. That would not provide useful information, unlike an occurrence map of a species. The idea was a holdover from the early version of LinEpig, hosted on Google's Picasa, where the map - available by default - was the only way to provide locality information. Most later-added images are linked to databased collection information. For specimens from non-databased collections, if we want to supply this information, it could better be  added via Narratives.
