### ISSUE TITLE
How to pull Summary Data field from Rights module

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#2]
In DETAIL.PHP: We're fetching it in the column array, but failing to grab the text of the field via below:

  $columns = array('irn', 'MulIdentifier', 'MulTitle', [...]'<erights:MulMultiMediaRef_tab>.(SummaryData)','<etaxonomy:MulMultiMediaRef_tab>.(ClaGenus,ClaSpecies,AutAuthorString)'); 
  foreach ($record['erights:MulMultiMediaRef_tab'] as $r_record) {
    $r = $r_record['SummaryData'];
  }

**Comment by slobulas** [comment]
I just pushed a new branch to the repo called, "rights-data". If this fix works for you, please merge it into the master branch, or let me know and I'll take care of it.

If there's something else you need for the Rights, just let me know.

**Comment by nsandlin** [comment]
That fixed it! This pulled in the "Usage, Current" string from the field content, which DetRights hadn't done; but that can (and now is) fixed in code. I'm noting it here only for future reference.

    DetRights:  
    [c] Field Museum 
    DetMediaRightsRef.(SummaryData)
    [(c) The Field Museum - CC BY-NC] - Usage, Current
