### ISSUE TITLE
Add catalog links to "View collection record"

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#20]
Externally databased specimens get a "View collection record" (see http://linepig.fieldmuseum.org/detail.php?irn=616587). This is fed via a Multimedia object containing the url. For specimens in the FMNH catalog, the link presented to the user should look the same; but it would be fed via a query to the Catalog module.  

```
// Adding collection record link
$collrecd = "";
if (!empty($record['RelRelatedMediaRef_tab'][0])) {
    if ($record['RelRelatedMediaRef_tab'][0]['MulMimeType'] == "x-url" && !empty($record['RelRelatedMediaRef_tab'][0]['MulIdentifier'])) {
        $collection_record_link = $record['RelRelatedMediaRef_tab'][0]['MulIdentifier'];
        if ($collection_record_link) {
        $collrecd = ' <span class="view-collection-record"><a href="' . $collection_record_link . '" target="_blank">View collection record</a></span>';
        }
    }
}
```

**Comment by slobulas** [comment]
Check RelRelatedMediaRef_tab for external links.
Check attached Catalogue records.

**Comment by slobulas** [comment]
Above commit introduces code that handles this issue. We will need to create Catalogue pages as well...

**Comment by nsandlin** [comment]
Make me an issue and I'll work on it

**Comment by slobulas** [comment]
I can set up a basic page if you can give me an IRN of a multimedia record that has reverse-attached Catalog records. :)

**Comment by nsandlin** [comment]
The first one, Anthrobia acuminata, should be one we have in the Catalog. I
believe that is the one I used in my example yesterday (about the
url) irn=3474248

**Comment by slobulas** [comment]
For the Catalogue page, add these following fields:

- on the DwC 1.2 tab, add the locality fields.
- Identified by
- DarIndividualCount
- Habitat

And others specified by Nina...

**Comment by slobulas** [comment]
Example Catalogue page: /catalogue/3474258

**Comment by slobulas** [comment]
Add Image to catalogue page and add catalogue record link on the Multimedia pages.

**Comment by slobulas** [comment]
Pending Nina's inspection of the spreadsheet import...
