### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by peteherbst** [nsandlin/linepig#24]
Once we have refactored the code into a framework, do pagination.

**Comment by slobulas** [comment]
AFTER LAUNCH

**Comment by peteherbst** [comment]
Umm, I'm going to take a crack at this now.

**Comment by nsandlin** [comment]
Yeah, we're up over 400 items on the homepage. But it would be good to Previous/Next (#91) before we push pagination to live.

**Comment by peteherbst** [comment]
I will look at #91 next. Pagination has been implemented, closing this out.
