### ISSUE TITLE
Replace NotNotes irn with OtherNumber

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#3]
In DETAILS.PHP & DETAILS2, we should be using the irn for the taxon coming from Other Number (the NotNotes field was a quick-fix and may not be populated going forward). Should make sure we are reliably grabbing the value for taxonomy, as there may be other Other Numbers in future.

   $taxo_irn = $record['NotNotes']; //replace with MulOtherNumber_tab

**Comment by slobulas** [comment]
Fixed.
