### ISSUE TITLE
Add GUID to collection record pages

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#50]
Like what we have on a detail page when it's associated with an FMNH catalog record. Sharon writes:

So for example:
https://linepig.fieldmuseum.org/catalogue/3474264 

would have " df1a4e49-c6a0-4035-8f43-1e9002f2c477  " if you where super cunning you could construct the persistant URL

https://db.fieldmuseum.org/df1a4e49-c6a0-4035-8f43-1e9002f2c477

The EMu logic is AdmGUIDValue_tab WHERE AdmGUIDIsPreferred_tab = Yes

**Comment by slobulas** [comment]
Yes, so this is just switching using the GUID in the URL, in place of the IRN.

I can do this if you'd like, up to you!

**Comment by nsandlin** [comment]
GUID added at last.

Not sure I want to switch up the persistent right away, especially not to something with a 36-char meaningless string instead of a 7-char one; but I'm willing to hear why I should want to. Let's make that a separate issue if so.
