### ISSUE TITLE
Adding a link to the external specimen collection record

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#6]
In DETAIL.PHP: We're fetching etaxonomy:MulMultiMediaRef_tab in the column array, but do we need to path to it via "B" - and if so, then do we have to http-request it, the same way we do the images? (A temporary mockup of the desired result is here http://linepig-dev.fieldmuseum.org/link-collrecord.html - "View collection record")

 A.
  $columns = array('irn', 'MulIdentifier', 'MulTitle', [...]'<etaxonomy:MulMultiMediaRef_tab>.(ClaGenus,ClaSpecies,AutAuthorString)'); 
  foreach ($record['erights:MulMultiMediaRef_tab'] as $r_record) {
    $r = $r_record['SummaryData'];
  }

  B.
  foreach ($image['resources'] as $resource) {
    $identifier = $resource['identifier'];
  }

**Comment by slobulas** [comment]
I'm confused as to what you're asking for in this issue. So I'm going to try to clarify.

Do you want me to work on the link for "View collection record"? Setting up the collection record link using the reversed attached Taxonomy record? (from the multimedia)

**Comment by slobulas** [comment]
Please take a look at my pull request and close this issue if you're happy with the code. Have a good one!

**Comment by nsandlin** [comment]
Swell!
