### ISSUE TITLE
Replace IMu with XML export

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#63]
Convert search import and detail pages to use Sqlite instead of IMu.

If possible, include additional fields to support search functionality enhancements detailed in Issue #62

**Comment by peteherbst** [comment]
Working on implementation in the [db-xml-import](https://github.com/nsandlin/linepig/tree/db-xml-import) branch.

Making decent progress already. I will have Pat help me set up a test environment so you can provide me feedback as I implement this.

**Comment by nsandlin** [comment]
I am SO thrilled! ... As I recall, a couple of the fields are for
enhancements that we'd long talked about (like search by photographer and
where the specimen is located (what institution)). And a lot of the fields
are just for making the "view collection record" page, for the tiny and
shrinking proportion of the images that are in our collection rather than
loans or contributed images.

I had to do a preliminary mapping just to assemble the export, of course. I
will need to go over it carefully next week.

**Comment by peteherbst** [comment]
Completed with v2.0 

Backend switched over to MongoDB.
