### ISSUE TITLE
Replace lookup-file with API call? (BOLD API)

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#7]
The BOLD Systems url is machine-predictable, but not all species have a BOLD taxon page. We are using a manually fetched lookup page - a list of all linyphiid taxa - which works well but requires  occasional updating. I should see if the API would return the taxon page; and if so, would checking during the DETAIL.PHP page build wreck performance. Note: keep in mind other other possible .outlinks to be done the same way, eg SCAN Symbiota

  http://www.boldsystems.org/index.php/TaxBrowser_TaxonPage?taxon=Genus+species

**Comment by slobulas** [comment]
AFTER LAUNCH

**Comment by nsandlin** [comment]
The BOLD Systems lookup list - direct link: 
http://boldsystems.org/index.php/TaxBrowser_TaxonPage/SpeciesSummary?taxid=1266

This looks like the equivalent of the API, except using ../index.php/API_Tax/TaxonData? rather than ../index.php/TaxBrowser_TaxonPage/ - the main difference procedurally is that instead of a directly parseable JSON it returns a human-readable spreadsheet, which requires further processing. 

The REST API for Taxonomy Browser does not have a "species list" or "SpeciesSummary" parameter that I could find.

Narrative steps (like if you lose the direct link):
Go to Bold Systems 
  http://boldsystems.org/
Select Taxonomy 
  http://boldsystems.org/index.php/TaxBrowser_Home
Enter "Linyphiidae" in the "Search Taxonomy" box 
  http://boldsystems.org/index.php/Taxbrowser_Taxonpage?taxon=Linyphiidae&searchTax=
Click on "Species List - Progress" in the BOLD Stats box
  http://boldsystems.org/index.php/TaxBrowser_TaxonPage/SpeciesSummary?taxid=1266
Select all
Open Excel or your favorite spreadsheet app
Drop into A1; Delete rows 1-5 (the headers) 
Copy the column B into a plain text file
Name it lookup-bold.txt and replace the old on on spice

Note: There is no need to clean out the non-erignine species, or the provisional species (like "Pocobletus sp. 10 FML" as they simply will not match any requests coming from LinEpig IMU.

**Comment by slobulas** [comment]
Use this page to grab the species names: http://boldsystems.org/index.php/TaxBrowser_TaxonPage/SpeciesSummary?taxid=1266

**Comment by slobulas** [comment]
This functionality is done. How it works now is that we can import all of the BOLD taxon values into the local Sqlite database via a command function I created for Laravel. It populates a `bold` table with the genus/species list. 

Then in the App\Multimedia model, we pull the genus/species value from the Sqlite database in order to construct the URL out to bold systems.

If you're curious about the code for this, we can talk about it tomorrow.
