### ISSUE TITLE
Previous/Next navigation

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#91]
From inside a Detail page, it would be very useful to be able to move to the next or previous image. This would avoid constantly going back to the homepage just to see the these item, or to toggle between two, especially in genera where many species are already represented in the gallery.

The logic would need to reflect the sequentially next/previous item as shown on the homepage (not by upload date, irn, etc.). However, the mechanism does not need to know what's on the homepage as such, since the target item would be the alphabetically next or previous item by MulTitle where DetSubject is "primary" (which can only be a Detail page for a female epigynum).

**Comment by nsandlin** [comment]
Hm, but it would also make sense, if the user came to the Detail page from a subset, to show the next/previous item in the subset (which might have a number of images not show on the homepage)...

**Comment by peteherbst** [comment]
Implemented via #99 

This update doesn't cover the subset page, we can revisit that later if you'd like. I've added previous and next links to the top of the multimedia detail page.

**Comment by nsandlin** [comment]
It's exciting to see this. But it's not limiting the images that show up to ones where DetSubject is "primary" (which can only be a Detail page for a female epigynum).

**Comment by peteherbst** [comment]
Roger that, reopening this issue to make that adjustment.

**Comment by peteherbst** [comment]
Ok, I've fixed that issue.

Close via 07f781bfa38e0568032078f87c4d2ef5e5300c04
