### ISSUE TITLE
Links to external collection records not showing up

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#92]
I just noticed this. Not sure if it has something to do with the fix we made in August, to keep the "BOLD systems taxon page" from pointing to the collection record after the switch to MongoDB, or if it happened later.

For images with a Field Museum collection record, there is still a link, like:
https://linepig.fieldmuseum.org/multimedia/616578

But for images with an external collection records, there is no link, like
https://linepig.fieldmuseum.org/multimedia/1388273
https://linepig.fieldmuseum.org/multimedia/616610

The external records come from the url in the RelRelatedMediaRef_tab field of the Multimedia record. The notes I made in August (attached) have some screenshots of how it's supposed to look (bottom pics), so it was working then.

[Notes-Mongo-Aug25.docx](https://github.com/nsandlin/linepig/files/11003750/Notes-Mongo-Aug25.docx)

**Comment by nsandlin** [comment]
I searched EMU for Multimedia that should have external collection record and none of the ones I spot-checked (of the 521 results) had one.
  Creator = LinEpig (177281)
  DetResourceType = Stillimage
  RelRelationship_tab = Associated Specimen URL

**Comment by peteherbst** [comment]
Please check my fix, it was definitely a bug.

Fixed by 50b324710c12574bbfcb5ee52097b1f30a0171b8

**Comment by nsandlin** [comment]
Beautiful!! And sooo fast!
