### ISSUE TITLE
Corrections not showing up

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#94]
The mechanism for displaying corrections in LinEpig has apparently fallen out. It involved an Narrative attached to the Taxonomy record and connected to the incorrectly identified Multimedia object.

An example is Oreonetides vaginatus, which should have an image in the notes section at bottom with a note reading "Image previously identified as Oreonetides vaginatus." 
https://linepig.fieldmuseum.org/multimedia/1245798

Mul irn 1245798
Taxo irn 537638
Narr irn 4076

Currently there appear to be only two corrections set up this way in EMu, but more now need to be posted, and further corrections are expected shortly.

Attached is a workflow how-to, in case it is useful. 

A possibly related issue has to do with annotations. We have been making taxonomy annotations using the Multimedia NteText() field, like for Erigone canthognatha (Mul irn 616651), "Female undescribed. This specimen with males and other females collected in Utah in 1964, det W. Ivie." The rationale was that this note had to do with this particular image (or at least, this specimen). But it makes more sense to have the portion relating to the taxon - "Female undescribed." - appear as a Narrative related to the Taxonomy record, especially in the case of disputed taxonomies. Also, we encountered problems with the annotions earlier when the Note was not in the NteText(0) field.  (I realize that 
[Howto-make LinEpig corrections in EMu.docx](https://github.com/nsandlin/linepig/files/11201687/Howto-make.LinEpig.corrections.in.EMu.docx)
Taxonomy annotations needs to be its own github issue, but is noted here in case of shared dependencies.)

**Comment by peteherbst** [comment]
For the correction, how do I determine what the old taxon determination was? (see this screenshot of my local dev). I currently have "(missing)" for that taxon section.

![Screenshot 2023-04-18 at 2 15 58 PM](https://user-images.githubusercontent.com/775699/232882726-a0318a29-08a7-4ca4-835e-49862ecd38d4.png)

**Comment by nsandlin** [comment]
This was always a little mind-bending, but basically the good image (Mul 1245798) is connected to the Taxonomy (Taxo 537638) which has an attached Narrative with title: LinEpig image correction (Narr 4076). And that Narrative has the old, bad image (Mul 616726) attached in its Multimedia tab. The taxon of the old, bad image would have been adjusted accordingly. ... Issue #49 from 2019 is about displaying a bit more of useful information about the old, bad image.

**Comment by peteherbst** [comment]
I believe I have a fix in place on the dev/test site. Please take a look when you get the chance. (you have to be on VPN or in the building).

https://linepig.fieldmuseum.tech/multimedia/1245798

**Comment by nsandlin** [comment]
I'm in the building (because Tuesday). Yes! That works. We just need to make the old, bad image - or possibly the whole container, whichever is easier right now - smaller, maybe like a quarter that size.  

A thought for the near future, but not for today, is that we want to anticipate there being more than one different image being incorrectly identified as a particular taxon, so their should be able to line up. (The ideal later would be to have them click through to their own Detail page).

**Comment by peteherbst** [comment]
I've reduced the size of the image, please take a look.

https://linepig.fieldmuseum.tech/multimedia/1245798
