### ISSUE TITLE
"Recently added"

### ISSUE THREAD

**Issue by nsandlin** [nsandlin/linepig#95]
It would be useful to have a list at the top of the homepage of species added recently (within the last 3 or 4 months). 

Could this be automated? It would be a list of the species names of Images uploaded with x days that have "primary" in the DetSubject field. If zero, the "Recently added: " label would go away (or div display:none).

![recently-added](https://user-images.githubusercontent.com/5316617/232797491-082f47f0-c0a1-4a6c-a505-4720ed9bae35.png)

**Comment by peteherbst** [comment]
I can check the AdmDateModified or AdmDateInserted field(s), looking back n number of weeks/months and display those at the top. Either using the design you listed here, or we could have something like an extra block at the top that has the most recent records.

Thoughts?

**Comment by nsandlin** [comment]
I don't think we need anything very fancy design-wise - either a color to make it eye-catching or a border, whatever, so it people see that it's an update. The most important things are a) making sure that it's only new primary epigynum pics (not males or habitus or  additional pics of species already listed on the main page), and b) having it close up when there's nothing new.  ...  Maybe it should say "Recently added or updated:" since that would cover corrections and replacment images.

**Comment by peteherbst** [comment]
Recently added block has been added to the homepage: https://linepig.fieldmuseum.org/

**Comment by peteherbst** [comment]
Reopening so we can fix which records should display.

**Comment by peteherbst** [comment]
I'm using the AdmDateModified field to determine which records have been recently updated. I'm not sure if I should be using a different field to get recent records.

**Comment by nsandlin** [comment]
Well, I'm not sure either. I can take a look next week and see if any bright thoughts occur to me. Although off the top, I think we want records added, not records modified (and only if they they have "primary" in the keywords).

Let's turn it off for now, and we can sort it out.

**Comment by nsandlin** [comment]
Ha ha, yeah, I can just picture that. ... I don't think we want "modified"
because wouldn't that pick up any time we touch a record? I can't look at
it right now, but isn't there an inserted/added field. And it should only
be for records that have "primary" (or "Primary") in the keywords field.
That would exclude all the records that are not epigyna.

**Comment by peteherbst** [comment]
I've removed this from the homepage until we've figured this out too.

**Comment by nsandlin** [comment]
Happiness
